name: BuildKernel

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up env
        run: |
          echo "安装依赖"
          sudo apt update -y
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip zipalign language-pack-zh-hans
      - name: pull
        run: |
          echo "拉取源码和拉取buildtools"
          git clone --depth=1 https://github.com/alk3p/android_kernel_xiaomi_sm8250 -b apollo-q-oss
          echo "拉取源码完成"
          mv android_kernel_xiaomi_sm8250 kernel_apollo
          mkdir build-tools
          cd build-tools
          git clone --depth=1 https://github.com/kdrag0n/proton-clang -b master
          git clone --depth=1 https://github.com/alk3p/AnyKernel3 -b master
          mv AnyKernel3 anykernel
          cd anykernel
          rm -rf modules
          rm -rf patch
          rm -rf ramdisk
          rm -rf README.md
          rm -rf anykernel.sh
          wget https://gist.githubusercontent.com/ckn4/e5a7864f344d481d7c0337c845a2bdc9/raw/anykernel.sh
          echo "拉取buildtools完成"
          cd
      - name: build with build.sh
        run: |
          echo "开始进行kernel构建"
          cd kernel_apollo
          wget https://raw.githubusercontent.com/alk3p/build-scripts/apollo/build.sh
          chmod +x build.sh
          ./build.sh
      - name : upload kernel
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: kernel
          path: ${{ github.workspace }}/kernel_apollo/arch/arm64/boot/Image.gz
      - name : upload zip
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: kernel_zip
          path: ${{ github.workspace }}/kernel_apollo/HiiraKernel*.zip
